### ISSUE TITLE
Website improvements TODO

### ISSUE THREAD

**Issue by ceball** [holoviz/datashader#542]
* [x] Homepage 'other resources' looks ugly (either align with previous block, or have previous block expand sooner after the twitter feed
* [x] Add a gallery (moved to #1030 )
* [x] put full-sized logo with wordmark on homepage (https://github.com/pyviz/nbsite/issues/31)
* [x] make sure logo is transparent, scalable, etc. if appropriate for each version (https://github.com/pyviz/nbsite/issues/40)
* [x] Create a datashader style (color scheme, etc)
* [x] The API docs don't start out with anything useful; is that a datashader or an nbsite issue? https://bokeh.github.io/datashader-docs/api.html
* [x] Upload site to s3, where datashader.org is registered, and delete datashader-docs (or add redirect). Update docs/README.md to reflect this.
* [x] make footer into a single line, without a TOC (jbednar: I think footers should be minimal, and the TOC is duplicative). (see https://github.com/ioam/sphinx_ioam_theme/issues/3)
* [x] ensure notebooks have links to files within the repository rather than direct links to files on github (i.e. replace links like `https://raw.githubusercontent.com/bokeh/datashader/master/docs/images/pipeline2.png`). [EDIT: covered by #619]
* [x] minor formatting issues noted in comments below
* [x] should be https (gets more important over time...). An authorized person (not sure who) will need to follow something like https://github.com/pyviz/nbsite/wiki#setting-up-https-for-aws
* [x] Update to the current Holoviz theme

**Comment by ceball** [comment]
@jbednar, re. "Add a gallery": generated from specific "gallery" notebooks (as is done for holoviews at http://holoviews.org/gallery/index.html and geoviews at https://ioam-docs.github.io/geoviews-master/gallery/index.html), or by collecting (some?) images from all (?) notebooks, or what?

**Comment by jbednar** [comment]
Good question!  I don't think the "reference gallery" concept from HoloViews is appropriate here, because there are only four fundamental objects in datashader (point, line, raster, and trimesh), which doesn't make for much of a reference gallery.  Each of those already has a whole section in the user manual anyway (at least on my own hard drive).

Conversely, I really think the amazing images from each of the various user guides and topic notebooks are very unlikely to get discovered by a random visitor unless we expose them somewhere close to the top level.  

So, I personally think that all images in notebooks should end up in some gallery-like representation unless we've included something explicitly in the notebook (metadata? comment? whatever?) to suppress it.  It could be a separate link for the "gallery" that really just collects whatnot from everywhere and links off to it, or it could be thumbnails to the right of each section in the user guide table of contents?

(And you already know I have the same opinion about the galleries -- they should be showing *all* the various images there unless otherwise directed, not just one representative image.)

**Comment by ceball** [comment]
Minor issues I noticed - "covering the range..." & bullet list formatting:

![screen shot 2018-03-16 at 10 35 27 am](https://user-images.githubusercontent.com/1929/37516405-e563d730-2905-11e8-88e0-e4046681d162.png)

**Comment by jbednar** [comment]
Finally done, only 5 years later. Thanks, @maximlt !
