### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#968]
The docs are missing some pretty important bits:

- [x] Polygons: Support added in https://github.com/holoviz/datashader/pull/819, but there's no polygon section in the user guide.
- [ ] Points: still just a link to NYC Taxi
- [x] [2D categorical colormapping](https://github.com/holoviz/datashader/pull/1020): needs examples (now in #1071)
- [x] Antialiasing: should be shown in documentation, at least in Timeseries.ipynb (now in #1071)
- [x] category_modulo and category_binning: https://github.com/holoviz/datashader/issues/1014
